### ISSUE TITLE
fcn32model = fcn32_blank(image_size) generates the "TypeError: index must be integers"

### ISSUE THREAD

**Issue by wenouyang** [mzaradzki/neuralnets#1]
Hi, thanks for sharing the code.

I have been trying to experiment with the code of `fcn16s_segmentation.ipynb`. However, the line of code `fcn32model = fcn32_blank(image_size)`  causes the following error message,  what can be the reason for this? Thanks.

> Using Theano backend.
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    fcn32model = fcn32_blank(image_size)
  File "/home/FCN/fcn16s/utils.py", line 78, in fcn32_blank
    (extra_margin/2, extra_margin/2))) ) # INFO : cropping as deconv gained pixels
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/models.py", line 332, in add
    output_tensor = layer(self.outputs[0])
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/layers/convolutional.py", line 1817, in call
    self.cropping[1][0]:-self.cropping[1][1]]
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/var.py", line 540, in __getitem__
    return theano.tensor.subtensor.advanced_subtensor(self, *args)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/subtensor.py", line 2140, in make_node
    index = tuple(map(as_index_variable, index))
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/subtensor.py", line 2081, in as_index_variable
    return make_slice(idx)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/type_other.py", line 39, in make_node
    list(map(as_int_none_variable, inp)),
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/type_other.py", line 20, in as_int_none_variable
    raise TypeError('index must be integers')
TypeError: index must be integers

**Comment by mzaradzki** [comment]
Hi
Thanks for the feedback

b) Did you 512 for image_size ?
I know that I can further improve the handling of image_size for odd numbers for example but I dont think this is the problem here.

a) Did you run the notebook as it is or did you modify it somewhere ?
If you modified it can you give me a github link for me to run it ?

**Comment by wenouyang** [comment]
Hi, Thanks a lot for your reply.

I exactly followed your code of `fcn16s_segmentation.ipynb`.  Due to the system constraints, I did not use notebook, and just copied your code into python file to run. To reproduce your training process, I just copied (segment of code)-by-(segment of code) and run, just the same as running the ipynb file in notebook. In specific, the above error messages occurs after I start to run `fcn32model = fcn32_blank(image_size)`

The image size is defined exactly the same as your code as `image_size=64*9` . I have not started to input my image.

Or in other words, I got those error messages after running the following code segment. Thanks.

```
from PIL import Image
import numpy as np
import math
import copy
import skimage.io as io
from scipy.misc import bytescale
from keras.models import Sequential, Model
from keras.layers import Input, Dense, Flatten, Dropout, Activation, Lambda, Permute, Reshape
from keras.layers import Convolution2D, ZeroPadding2D, MaxPooling2D, Deconvolution2D, Cropping2D
from keras.layers import merge
from keras import backend as K
from utils import fcn32_blank, fcn_32s_to_16s, prediction
K.set_image_dim_ordering('th') 
image_size = 64*9
fcn32model = fcn32_blank(image_size)
```

**Comment by mzaradzki** [comment]
Hi

Can you try a new test file with only the following?

```
from utils import fcn32_blank
image_size = 512
fcn32model = fcn32_blank(image_size)
```

Let me know if that one works. If yes we can build up from here.

**Comment by mzaradzki** [comment]
In particular I don't have this line in my code:
"K.set_image_dim_ordering('th')"

As your error message is about indices that may be part of the problem.

**Comment by mzaradzki** [comment]
One last suggestion, did you follow these instructions ?
https://keras.io/backend/

That solved my problems when I started using Keras the first time on VGG model.

**Comment by wenouyang** [comment]
Hi,

Thanks for your advice.

I tried as you suggested, only compiling a script with those three lines of code, but it still gets the following error message. As you can see, I am using Theano backend, which was setup following the Keras instructions as well.  Thanks.

> python train-test.py
Using Theano backend.
Traceback (most recent call last):
  File "train-test.py", line 3, in <module>
    fcn32model = fcn32_blank(image_size)
  File "/home/ugwz/GPU-Study/keras/FCN/fcn16s/utils.py", line 78, in fcn32_blank
    (extra_margin/2, extra_margin/2))) ) # INFO : cropping as deconv gained pixels
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/models.py", line 332, in add
    output_tensor = layer(self.outputs[0])
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/Keras-1.2.1-py3.4.egg/keras/layers/convolutional.py", line 1817, in call
    self.cropping[1][0]:-self.cropping[1][1]]
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/var.py", line 540, in __getitem__
    return theano.tensor.subtensor.advanced_subtensor(self, *args)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/subtensor.py", line 2140, in make_node
    index = tuple(map(as_index_variable, index))
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/subtensor.py", line 2081, in as_index_variable
    return make_slice(idx)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/type_other.py", line 39, in make_node
    list(map(as_int_none_variable, inp)),
  File "/devl/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/tensor/type_other.py", line 20, in as_int_none_variable
    raise TypeError('index must be integers')
TypeError: index must be integers

**Comment by mzaradzki** [comment]
Hi @wenouyang 

I notice something strange in your error message ; they refer to tensorflow packages but the code tries to run on Theano backend. I am not sure this is "normal".

Something that may help check things are in order, can you run the VGG code sample from this repo:
https://github.com/fchollet/deep-learning-models

**Comment by wenouyang** [comment]
Hi, I have tried to run the vgg16.py in https://github.com/fchollet/deep-learning-models  
It turns out I have a lot of error. The keras version I am using is 1.2.1, and I am not sure whether they are using the latest version. Which keras version you are using? Thanks.

**Comment by mzaradzki** [comment]
hi
This code repo is from the author of Keras (fchollet) so I think you should make sure this works fine.
The fact you have TensorFlow error while you specify Theano as a backend is very surprising to me for example.

Have you tried using conda/anaconda to create a dedicated clean python environment ?

Alternatively this blog shows how to install Keras/tensorflow using virtualenv:
http://www.pyimagesearch.com/2016/11/14/installing-keras-with-tensorflow-backend/

Personally I use AWS to run my tools but if I were to use my laptop I would definitely using conda or virtualenv to avoid configuration conflicts.

**Comment by wenouyang** [comment]
Thanks.
